# Default values for kubeflex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: localtest.me
externalPort: "9443"
isOpenShift: "false"
installPostgreSQL: true
hostContainer: kubeflex-control-plane
verbosity: 0