apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      containers:
      - name: "{{ .Release.Name }}"
        image: bitnami/kubectl:1.27.8
        command:
        - sh
        - -c
        - |
          kubectl apply -f /etc/kube/hooks.yaml
        volumeMounts:
        - name: hooks
          mountPath: "/etc/kube"
          readOnly: true    
      restartPolicy: OnFailure
      volumes:
      - name: hooks
        secret:
          secretName: postcreate-hooks
      restartPolicy: Never
  backoffLimit: 4 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postcreatehooks
rules:
- apiGroups: ["tenancy.kflex.kubestellar.org"]
  resources: ["postcreatehooks"]
  verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postcreatehooks-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{.Release.Namespace}}'
roleRef:
  kind: ClusterRole
  name: postcreatehooks
  apiGroup: rbac.authorization.k8s.io