apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: openshift-crds
  labels:
    kflex.kubestellar.io/flavor: openshift
spec:
  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "{{.HookName}}"
    spec:
      template:
        spec:
          containers:
          - name: "{{.HookName}}"
            image: quay.io/pdettori/helm:v3.13.2
            args:
              - upgrade
              - --install
              - "{{.HookName}}"
              - oci://quay.io/pdettori/openshift-crds
              - --version
              - "0.1.0"
            env:
            - name: KUBECONFIG
              value: "/etc/kube/kubeconfig-incluster"    
            volumeMounts:
            - name: kubeconfig
              mountPath: "/etc/kube"
              readOnly: true  
          volumes:
          - name: kubeconfig
            secret:
              secretName: admin-kubeconfig
          restartPolicy: Never
      backoffLimit: 1
