name: CI
on:
  pull_request:
    branches:
      - main
      - "release-*"
jobs:
  ci-checks:
    runs-on: ubuntu-latest
    name: CI Checks
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version: "1.24.5"
      - name: Lint
        run: go fmt ./...
      - name: Static analysis
        run: go vet ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
